### ISSUE TITLE
Unsupported JavaFX configuration

### ISSUE THREAD

**Issue by stefanDeveloper** [Sharknoon/siedler-von-catan#2]
I got the following issue:

    WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4ccc0db7'
    Graphics Device initialization failed for :  es2, sw
    Error initializing QuantumRenderer: no suitable pipeline found
    java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	    at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	    at java.base/java.lang.Thread.run(Thread.java:831)
    Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	    ... 1 more
    Exception in thread "main" java.lang.RuntimeException: No toolkit found
	    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
	    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	    at java.base/java.lang.Thread.run(Thread.java:831)

I ran `java -jar siedler-von-catan-2.3.0.jar` with the following java version:

    java version "16" 2021-03-16
    Java(TM) SE Runtime Environment (build 16+36-2231)
    Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

**Comment by sharknoon** [comment]
Hi Stefan,
thanks for giving this game a try 🙂

I was able to reproduce your issue:
![grafik](https://user-images.githubusercontent.com/16149608/119190721-048e1c80-ba7e-11eb-8431-6adcb6a84538.png)

The problem consists of two things, first, you need to have JavaFX installed and secondly you have to specify the needed modules on the startup of the jar.
![grafik](https://user-images.githubusercontent.com/16149608/119191108-82eabe80-ba7e-11eb-8cd8-efd51814f977.png)

I have added a detailed description in the README.

Please let me know if that fixes your problem

Kind regards

Your fellow student

Sharknoon

**Comment by sharknoon** [comment]
Please reopen this issue if it persists
